### ISSUE TITLE
Loose HTTP client coupling

### ISSUE THREAD

**Issue by xabbuh** [xabbuh/panda-client#6]
At the moment, the library has a hard dependency on the Guzzle HTTP library. The library should rather depend on an abstract HTTP layer (for example `egeloen/http-adapter`).

**Comment by killerwolf** [comment]
why not the more standard psr/http-message ?

**Comment by xabbuh** [comment]
At the time of opening this issue PSR-7 wasn't a thing yet. A solution created now should rather use HTTPlug which is based on the PSR-7 messages.

**Comment by stof** [comment]
@xabbuh would be great to work on this, because the ``guzzle/guzzle`` dependency forbids updating to Symfony 3

**Comment by xabbuh** [comment]
Yeah indeed, I was thinking about doing some other refactoring work that would require a major version bump too, but that could as well be postponed to a potential future 3.0 release.
