### ISSUE TITLE
Guzzle update

### ISSUE THREAD

**Issue by tim-hanssen** [xabbuh/panda-client#7]
Hey guys,

Would it be possible to start using a new version of Guzzle ( at least 5 > ).
We're running in some issue because the amazon SDK requires 5.

**Comment by xabbuh** [comment]
I was thinking about creating a new major version which would along with other features not rely on Guzzle any more, but instead use an HTTP client abstraction library. Though according to my plans the API of the library would change then too.

Is it an option for you to adapt these changes or do you prefer a version with more freedom in choosing the actual HTTP client, but without breaking changes in the API?

**Comment by tim-hanssen** [comment]
Hey!

That sounds good; we could easily change our platform to communicate with a changed API.
I think Guzzle works great, but maybe a HTTP client abstraction library is more core without all the unnecessary code in a project like Guzzle.

**Comment by stof** [comment]
@xabbuh I guess you refer to https://github.com/php-http ?

**Comment by xabbuh** [comment]
@stof yes (I had https://github.com/egeloen/ivory-http-adapter in mind, but they seem to have moved)

**Comment by xabbuh** [comment]
`php-http/httplug` now has a stable release.

**Comment by phoenixgao** [comment]
Since composer started to give out this warning loudly:

"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

Is there any news for this?

btw I'm not against to use guzzle6 because guzzle utilizes PSR-7 as the HTTP message interface.

**Comment by xabbuh** [comment]
@phoenixgao I did not find the time to do that till now. If you'd like to open a PR, I'd by happy to review it.

**Comment by xabbuh** [comment]
Closing this one in favour of #6.
